permalink: /:year/:month/:day/:title
name: Bradly Feeley
author: Bradly Feeley
tagline: San Diego Ruby on Rails Developer
twitter: bradly
github: bradly
google_analytics_id: 'UA-537540-7'
pygments: true
